export default [
  {
    login: "codersait",
    id: 34860861,
    node_id: "MDQ6VXNlcjM0ODYwODYx",
    avatar_url: "https://avatars.githubusercontent.com/u/34860861?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/codersait",
    html_url: "https://github.com/codersait",
    followers_url: "https://api.github.com/users/codersait/followers",
    following_url:
      "https://api.github.com/users/codersait/following{/other_user}",
    gists_url: "https://api.github.com/users/codersait/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/codersait/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/codersait/subscriptions",
    organizations_url: "https://api.github.com/users/codersait/orgs",
    repos_url: "https://api.github.com/users/codersait/repos",
    events_url: "https://api.github.com/users/codersait/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/codersait/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "krebyancode",
    id: 81440911,
    node_id: "MDQ6VXNlcjgxNDQwOTEx",
    avatar_url: "https://avatars.githubusercontent.com/u/81440911?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/krebyancode",
    html_url: "https://github.com/krebyancode",
    followers_url: "https://api.github.com/users/krebyancode/followers",
    following_url:
      "https://api.github.com/users/krebyancode/following{/other_user}",
    gists_url: "https://api.github.com/users/krebyancode/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/krebyancode/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/krebyancode/subscriptions",
    organizations_url: "https://api.github.com/users/krebyancode/orgs",
    repos_url: "https://api.github.com/users/krebyancode/repos",
    events_url: "https://api.github.com/users/krebyancode/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/krebyancode/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Halityildiz",
    id: 86552701,
    node_id: "MDQ6VXNlcjg2NTUyNzAx",
    avatar_url: "https://avatars.githubusercontent.com/u/86552701?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Halityildiz",
    html_url: "https://github.com/Halityildiz",
    followers_url: "https://api.github.com/users/Halityildiz/followers",
    following_url:
      "https://api.github.com/users/Halityildiz/following{/other_user}",
    gists_url: "https://api.github.com/users/Halityildiz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Halityildiz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Halityildiz/subscriptions",
    organizations_url: "https://api.github.com/users/Halityildiz/orgs",
    repos_url: "https://api.github.com/users/Halityildiz/repos",
    events_url: "https://api.github.com/users/Halityildiz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Halityildiz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "savasgormus",
    id: 86850875,
    node_id: "MDQ6VXNlcjg2ODUwODc1",
    avatar_url: "https://avatars.githubusercontent.com/u/86850875?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/savasgormus",
    html_url: "https://github.com/savasgormus",
    followers_url: "https://api.github.com/users/savasgormus/followers",
    following_url:
      "https://api.github.com/users/savasgormus/following{/other_user}",
    gists_url: "https://api.github.com/users/savasgormus/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/savasgormus/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/savasgormus/subscriptions",
    organizations_url: "https://api.github.com/users/savasgormus/orgs",
    repos_url: "https://api.github.com/users/savasgormus/repos",
    events_url: "https://api.github.com/users/savasgormus/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/savasgormus/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mustafatayfur",
    id: 87443652,
    node_id: "MDQ6VXNlcjg3NDQzNjUy",
    avatar_url: "https://avatars.githubusercontent.com/u/87443652?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mustafatayfur",
    html_url: "https://github.com/mustafatayfur",
    followers_url: "https://api.github.com/users/mustafatayfur/followers",
    following_url:
      "https://api.github.com/users/mustafatayfur/following{/other_user}",
    gists_url: "https://api.github.com/users/mustafatayfur/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mustafatayfur/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mustafatayfur/subscriptions",
    organizations_url: "https://api.github.com/users/mustafatayfur/orgs",
    repos_url: "https://api.github.com/users/mustafatayfur/repos",
    events_url: "https://api.github.com/users/mustafatayfur/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mustafatayfur/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hsynarsln",
    id: 90923579,
    node_id: "MDQ6VXNlcjkwOTIzNTc5",
    avatar_url: "https://avatars.githubusercontent.com/u/90923579?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hsynarsln",
    html_url: "https://github.com/hsynarsln",
    followers_url: "https://api.github.com/users/hsynarsln/followers",
    following_url:
      "https://api.github.com/users/hsynarsln/following{/other_user}",
    gists_url: "https://api.github.com/users/hsynarsln/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hsynarsln/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hsynarsln/subscriptions",
    organizations_url: "https://api.github.com/users/hsynarsln/orgs",
    repos_url: "https://api.github.com/users/hsynarsln/repos",
    events_url: "https://api.github.com/users/hsynarsln/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hsynarsln/received_events",
    type: "User",
    site_admin: false,
  },
];
