export default {
  login: "fearm3",
  id: 87443921,
  node_id: "MDQ6VXNlcjg3NDQzOTIx",
  avatar_url: "https://avatars.githubusercontent.com/u/87443921?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/fearm3",
  html_url: "https://github.com/fearm3",
  followers_url: "https://api.github.com/users/fearm3/followers",
  following_url: "https://api.github.com/users/fearm3/following{/other_user}",
  gists_url: "https://api.github.com/users/fearm3/gists{/gist_id}",
  starred_url: "https://api.github.com/users/fearm3/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/fearm3/subscriptions",
  organizations_url: "https://api.github.com/users/fearm3/orgs",
  repos_url: "https://api.github.com/users/fearm3/repos",
  events_url: "https://api.github.com/users/fearm3/events{/privacy}",
  received_events_url: "https://api.github.com/users/fearm3/received_events",
  type: "User",
  site_admin: false,
  name: "İbrahim",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Frontend Developer\r\nReactJS",
  twitter_username: null,
  public_repos: 86,
  public_gists: 0,
  followers: 6,
  following: 13,
  created_at: "2021-07-14T18:18:33Z",
  updated_at: "2022-01-21T20:51:00Z",
};
